// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// When VITE_REMEMBER_SESSION=true, sessions persist across browser restarts (localStorage).
// When false/unset (default), sessions are cleared on browser close (sessionStorage).
export const REMEMBER_SESSION = import.meta.env.VITE_REMEMBER_SESSION === 'true';

export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: REMEMBER_SESSION ? localStorage : sessionStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : null as unknown as ReturnType<typeof createClient<Database>>;
